package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/camilbinas/gude-agents/agent/tool"
)

// Document holds a text chunk and associated metadata.
type Document struct {
	ID       string // Storage-level ID. Empty on input = auto-generated by the store.
	Content  string
	Metadata map[string]string
}

// ScoredDocument pairs a Document with its similarity score.
type ScoredDocument struct {
	Document Document
	Score    float64
}

// Embedder converts text into a float vector.
type Embedder interface {
	Embed(ctx context.Context, text string) ([]float64, error)
}

// VectorStore stores document embeddings and performs similarity search.
type VectorStore interface {
	// Upsert stores documents with their embeddings. If a document's ID is empty,
	// the store generates one. If a document's ID already exists, the store
	// replaces the existing content, metadata, and embedding.
	// Returns the IDs of all stored documents in input order.
	Upsert(ctx context.Context, docs []Document, embeddings [][]float64) (ids []string, err error)

	// Search returns the top-K documents by similarity. Results include document IDs.
	Search(ctx context.Context, queryEmbedding []float64, topK int) ([]ScoredDocument, error)

	// Delete removes documents by their IDs. Returns nil if an ID doesn't exist.
	Delete(ctx context.Context, ids ...string) error
}

// VectorStoreManager extends VectorStore with document retrieval and
// metadata-based bulk deletion for full lifecycle management.
type VectorStoreManager interface {
	VectorStore

	// Find retrieves documents by their IDs. Returns documents in the same
	// order as the input IDs, omitting IDs that don't exist. Returns an empty
	// slice and nil error for an empty input.
	Find(ctx context.Context, ids ...string) ([]Document, error)

	// DeleteByMetadata deletes all documents whose metadata contains all
	// key-value pairs in the filter (AND semantics). Returns an error if the
	// filter is empty (safety guard against accidental full deletion).
	DeleteByMetadata(ctx context.Context, filter map[string]string) error
}

// Retriever retrieves relevant documents for a query.
type Retriever interface {
	Retrieve(ctx context.Context, query string) ([]Document, error)
}

// Reranker re-scores a candidate set of documents for a query.
type Reranker interface {
	Rerank(ctx context.Context, query string, docs []Document) ([]Document, error)
}

// FulltextSearcher performs keyword-based document search.
type FulltextSearcher interface {
	// Search returns documents matching the query, ordered by relevance score
	// descending. Returns an empty slice and nil error for empty queries.
	// Returns an error if limit < 1.
	Search(ctx context.Context, query string, limit int) ([]ScoredDocument, error)
}

// MetadataFilter represents AND-semantics metadata constraints.
// All key-value pairs must match for a document to be included.
type MetadataFilter map[string]string

// FilteredVectorStore extends VectorStore with metadata-filtered search.
// Backends opt into filtering by implementing this interface alongside VectorStore.
type FilteredVectorStore interface {
	VectorStore

	// SearchWithFilter returns the top-K documents by similarity whose metadata
	// contains all key-value pairs in the filter (AND semantics).
	// When filter is nil or empty, behaves identically to Search.
	SearchWithFilter(ctx context.Context, queryEmbedding []float64, topK int, filter MetadataFilter) ([]ScoredDocument, error)
}

// FilteredFulltextSearcher extends FulltextSearcher with metadata-filtered search.
// Backends opt into filtering by implementing this interface alongside FulltextSearcher.
type FilteredFulltextSearcher interface {
	FulltextSearcher

	// SearchWithFilter returns documents matching the query whose metadata
	// contains all key-value pairs in the filter (AND semantics).
	// When filter is nil or empty, behaves identically to Search.
	SearchWithFilter(ctx context.Context, query string, limit int, filter MetadataFilter) ([]ScoredDocument, error)
}

// ContextFormatter formats retrieved documents into a string for prompt injection.
type ContextFormatter func(docs []Document) string

// DefaultContextFormatter formats documents as numbered items wrapped in
// <retrieved_context> tags. The tags signal to the model that this content
// is external data and should not be interpreted as instructions.
var DefaultContextFormatter ContextFormatter = func(docs []Document) string {
	if len(docs) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("<retrieved_context>\n")
	for i, doc := range docs {
		fmt.Fprintf(&b, "[%d] %s\n", i+1, doc.Content)
	}
	b.WriteString("</retrieved_context>")
	return b.String()
}

// NewRetrieverTool wraps a Retriever as a tool.Tool so the LLM can
// decide when to retrieve. An optional ContextFormatter controls how
// documents are rendered in the tool result; DefaultContextFormatter is
// used when none is provided.
func NewRetrieverTool(name, description string, r Retriever, formatter ...ContextFormatter) tool.Tool {
	fmtFn := DefaultContextFormatter
	if len(formatter) > 0 && formatter[0] != nil {
		fmtFn = formatter[0]
	}

	schema := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"query": map[string]any{"type": "string"},
		},
		"required": []any{"query"},
	}

	return tool.NewRaw(name, description, schema, func(ctx context.Context, input json.RawMessage) (string, error) {
		var params struct {
			Query string `json:"query"`
		}
		if err := json.Unmarshal(input, &params); err != nil {
			return "", err
		}

		docs, err := r.Retrieve(ctx, params.Query)
		if err != nil {
			return "", err
		}

		if len(docs) == 0 {
			return "No relevant documents found.", nil
		}

		return fmtFn(docs), nil
	})
}
